"""Emit a pytest file: one test per failure class, parametrised over member repros."""

from __future__ import annotations

from pathlib import Path

from blindspot.types import AgentSpec, FailureClass

HEADER = '"""Generated by Blindspot. Each test is a failure class the author never wrote."""\n'


def emit_pytest(classes: list[FailureClass], spec: AgentSpec, path: Path) -> None:
    """crash class  -> assert terminal == 'ok'
    contract class  -> assert spec.contract(output)
    metamorphic     -> assert extract_answer(baseline) == extract_answer(mutant)
    quality (judge) -> xfail with the judge's reason, confidence in the message."""
    raise NotImplementedError
