"""Emit a pytest file: one test per failure class, parametrised over member repros."""

from __future__ import annotations

import re
from pathlib import Path

from blindspot.types import AgentSpec, FailureClass

HEADER = '"""Generated by Blindspot. Each test is a failure class the author never wrote."""\n'

MAX_PARAMS = 8


def _ident(text: str) -> str:
    """Sanitise an arbitrary string into a safe python identifier fragment."""
    cleaned = re.sub(r"\W+", "_", str(text).strip()).strip("_")
    return cleaned or "x"


def _baseline_of(finding) -> str:
    ev = finding.evidence or {}
    return ev.get("baseline_input") or ev.get("baseline") or finding.input


def emit_pytest(classes: list[FailureClass], spec: AgentSpec, path: Path) -> None:
    """crash class  -> assert terminal not in (error, timeout)
    contract class  -> assert spec.contract(output)
    metamorphic     -> assert extract_answer(baseline) == extract_answer(mutant)
    quality (judge) -> xfail with the judge's reason, confidence in the message."""
    attr = spec.name.upper()

    lines: list[str] = [
        HEADER.rstrip("\n"),
        "",
        "import pytest",
        f"from targets.specs import {attr} as SPEC",
        "",
        "",
    ]

    used: set[str] = set()
    blocks: list[str] = []

    for fc in classes:
        oracle = (fc.oracle or "oracle").lower()
        name = f"test_{_ident(oracle)}_{_ident(fc.id)}"
        base, n = name, 2
        while name in used:
            name = f"{base}_{n}"
            n += 1
        used.add(name)

        inputs = list(dict.fromkeys(m.input for m in fc.members))[:MAX_PARAMS]
        if not inputs:
            inputs = [fc.minimal_repro.input]

        if oracle == "metamorphic":
            by_input: dict[str, str] = {}
            for m in fc.members:
                by_input.setdefault(m.input, _baseline_of(m))
            fallback = _baseline_of(fc.minimal_repro)
            block = ["@pytest.mark.parametrize('inp,baseline', ["]
            block += [
                f"    ({inp!r}, {by_input.get(inp, fallback)!r})," for inp in inputs
            ]
            block += [
                "])",
                f"def {name}(inp, baseline):",
                "    assert SPEC.extract_answer(SPEC.entrypoint(baseline)) == "
                "SPEC.extract_answer(SPEC.entrypoint(inp))",
            ]
        elif oracle in ("judge", "quality"):
            # a judge finding is not deterministically re-checkable, so this is a
            # recorded verdict rather than a live assertion: it is skipped, and
            # `pytest -rs` prints the judge's reasoning next to the reproducer.
            reason = fc.minimal_repro.summary or fc.label or "judge oracle flagged this output"
            block = [
                f"@pytest.mark.skip(reason={reason!r})",
                "@pytest.mark.parametrize('inp', [",
                *[f"    {inp!r}," for inp in inputs],
                "])",
                f"def {name}(inp):",
                "    # re-running the judge here would need a live model; the finding",
                "    # is recorded above. Handle it by inspecting the agent's output:",
                "    run = SPEC.entrypoint(inp)",
                "    assert run.terminal != \"error\"",
            ]
        elif oracle == "schema":
            block = [
                "@pytest.mark.parametrize('inp', [",
                *[f"    {inp!r}," for inp in inputs],
                "])",
                f"def {name}(inp):",
                "    run = SPEC.entrypoint(inp)",
                '    assert run.terminal == "ok"',
                "    assert SPEC.contract(run.output)",
            ]
        else:  # crash and anything unrecognised
            # the invariant is "no unhandled crash" — a clean, explicit refusal
            # (terminal='refused') is a valid fix, not a failure.
            block = [
                "@pytest.mark.parametrize('inp', [",
                *[f"    {inp!r}," for inp in inputs],
                "])",
                f"def {name}(inp):",
                "    run = SPEC.entrypoint(inp)",
                '    assert run.terminal not in ("error", "timeout"), run.error_type',
            ]

        blocks.append("\n".join(block))

    if not blocks:
        blocks.append("def test_blindspot_placeholder():\n    pass")

    lines.append("\n\n\n".join(blocks))
    lines.append("")

    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
